extends Node
class_name EventStream

@warning_ignore("unused_signal")
signal join_race_attempted(username: String, profile_url: String)
@warning_ignore("unused_signal")
signal leave_race_attempted(username: String)
@warning_ignore("unused_signal")
signal trap_drop_attempted(username: String)
@warning_ignore("unused_signal")
signal missle_launch_attempted(username: String)
@warning_ignore("unused_signal")
signal joined_race(lurker: Lurker)
@warning_ignore("unused_signal")
signal lurker_chat(username: String)
@warning_ignore("unused_signal")
signal send_chat(message: String)
@warning_ignore("unused_signal")
signal send_to_pit(username: String)
@warning_ignore("unused_signal")
signal leave_the_pit(username: String)
@warning_ignore("unused_signal")
signal send_to_track(username: String)
